name: cult_radio
description: Cult Radio Flutter App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  firebase_core: ^2.24.0
  firebase_database: ^10.4.1
  youtube_player_flutter: ^8.1.2
  just_audio: ^0.9.35
  audio_service: ^0.18.9
  equatable: ^2.0.5
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true